### ISSUE TITLE
cache issues

### ISSUE THREAD

**Issue by eturino** [opentable/hobknob#130]
I know you're going to love this... 

_Randomly_, not always (I feel really bad about this), I get old views from hobknob. Audit data not appearing, toggles with old data...

I can see the fresh content in another browser, but I still see the stale data on the first one, even if I go see another section, another feature... 

I'm assuming it is something related to cache. It's driving us pretty crazy since we cannot trust that whatever we are seeing is the actual values of the toggles.

Any idea?

**Comment by eturino** [comment]
shouldn't be related at all, but we didn't noticed this problem before we introduced Auth...

**Comment by stevejhiggs** [comment]
Interesting, I don't think we've seen this issue. There's nothing adding any sort of cache header to the response is there?

**Comment by eturino** [comment]
Aha! Thanks a lot. Indeed it was in our setup. We have hobknob behind nginx and it was caching the response.
I'll close the issue.
