### ISSUE TITLE
Not an Issue: feature_toggle_service

### ISSUE THREAD

**Issue by eturino** [opentable/hobknob#131]
Not an issue, just wanted to point out the service that we're using in our ruby apps for checking the toggles managed by hobknob. It may be useful to other people.

Thanks :)

https://github.com/eturino/feature_toggle_service

**Comment by eturino** [comment]
BTW, it won't work currently for a normal hobknob configuration. We assume that we have always "Envs Features" (features with environment key: 'prd', 'development', 'test', 'int', 'uat', 'qa'...), similar to the domain features that comes from hobknob out of the box (just different keys).

I have not yet added the functionality of checking the normal feature toggle to resolve `FeatureToggleService.on? :feature` calls if the global toggle is defined.

**Comment by ryantomlinson** [comment]
Thanks for that @eturino . Can still be used as a reference for use in Ruby. I'm going to close this as an "issue" though.

**Comment by eturino** [comment]
sure :+1:

**Comment by stevejhiggs** [comment]
We could add it to the list of clients in the readme though

**Comment by eturino** [comment]
I could add some comments in my gem's README with the current limitations for hobknob usage if you want to list it.
