### ISSUE TITLE
Move out of the opentable repository

### ISSUE THREAD

**Issue by stevejhiggs** [opentable/hobknob#148]
Given that most of the people who work/worked on hobknob don't work for opentable and that opentable are not supporting it perhaps hobknob should be given it's own repo outside of the opentable one?

**Comment by matteofigus** [comment]
Hi @stevejhiggs,
  AFAIK OpenTable is keen on supporting this project. If you think we are not, how can we do better?

As our contributing guidelines states, we accepts contributions by everyone, so I can't see how this repo being inside OT organisation could be a limit?

Thanks
Matteo

**Comment by andyroyle** [comment]
I think hobknob should have its own org in order to hold all related repos (clients etc)

**Comment by andyroyle** [comment]
In terms of licensing the license will obviously remain with OT, but structurally I think a separate org is best.

**Comment by seif** [comment]
I don't think we envision OSS projects at opentable to be seperated into a different org when main contributors leave the company. Policy is still being defined but I would imagine that we'd prefer to keep them under the opentable org to show how brilliant we (or the people we hired and left) are.

In regards to the clients and structure separation, I imagine that #89 will help.

@richardhopton volunteered to be maintainer of hobknob today and an internal call for volunteers was sent out.

I'd prefer to leave everything as is for now and see how things progress. If it grows massively and we get a lot of contributions it might warrant a different org, but for the time being, I don't see the point.
