### ISSUE TITLE
V3 milestone

### ISSUE THREAD

**Issue by matteofigus** [opentable/hobknob#152]
I would like to create a V3 milestone. Perhaps working in a different branch.

Purposed breaking changes:
- update to latest etcd
- updated to latest stable node (4.X as now, it can be 6.X in a couple of months)
  - rewrite server-side code using some es2015
  - use the same version for docker

Feedbacks?

**Comment by tombuildsstuff** [comment]
Sounds good. For me personally - the most pressing issue is upgrading to the latest version of ETCD.

I've also been wondering if that's the best choice of persistence for Hobknob tbh, or if it'd be better to use something else with a larger community?

**Comment by chriscartlidge** [comment]
@tombuildsstuff This is actively been worked on at the moment. We have a roadmap to upgrade to 3.2.1 and will update you shortly on this.

**Comment by andyroyle** [comment]
we're running hobknob at VE using etcd 2.x, so I don't think there's any big blockers on this

**Comment by matteofigus** [comment]
Thanks Tom. I like the idea. Probably the ideal thing for me would be to have
* A simple hobknob server+ui with self hosted data (simple json files?)
* Plugin for etcd
* A system to potentially plug other db storages?

**Comment by chriscartlidge** [comment]
@andyroyle We have had it running fine locally with 2.3.1, it's the upgrade path that we need to managed for existing users.

**Comment by matteofigus** [comment]
Can you vote thumbs down or up for creating a new milestone + branch for this?

**Comment by tombuildsstuff** [comment]
@matteofigus one other question from me: rather than each client connecting to ETCD itself (and thus the ETCD server being distributed across multiple applications) - is it worth thinking about the clients connecting to ETCD via the Hobknob server / an API to get the status of a toggle?

**Comment by matteofigus** [comment]
@tombuildsstuff I think that makes sense also for security. If the webapp exposes an API to save the data, we can ensure authentication is used. Do you mind opening a specific issue for that? I could work on that when I have time.

**Comment by tombuildsstuff** [comment]
Turned v3 into a Milestone - https://github.com/opentable/hobknob/projects/1 - there's also a PR for the API #184
