### ISSUE TITLE
has anyone ever used the 'auditReplication' feature?

### ISSUE THREAD

**Issue by andyroyle** [opentable/hobknob#159]
I'm working on some refactors and I found [this code](https://github.com/opentable/hobknob/blob/master/server/src/hooks/auditReplication.js) which allows you to hook a listener to the audit service and get notified when audit events occur. 

It's seems to have been intended for writing audit-events to a separate data store, but i'm not sure that it's ever been used.

Seems a good candidate for removal IMHO.

**Comment by andyroyle** [comment]
speak now or forever be cherry-picking commits

**Comment by chriscartlidge** [comment]
Good to go for me 👍
