### ISSUE TITLE
does anyone object to me rewriting the ui in angular 2?

### ISSUE THREAD

**Issue by stevejhiggs** [opentable/hobknob#183]
There are some pretty big issues with the current ui structure. These include:

No bundling or minification of scripts
It's based on a pretty old version of angular and has never really received a lot of love

Rather than trying to fix this in place, which feels like a horrific task. I'm thinking of just recoding the thing in angular 2 (I was thinking react or ember but I thought I'd stick with something vaguely similar) and abstracting away the bits where the ui talks to hobknob.

Visually there would be very little difference, it's purely a structural change.

I would propose that this be part of v3

**Comment by tombuildsstuff** [comment]
@stevejhiggs sounds good to me - I've got some UI tests which I've built around the current html which I'm planning to use post-deployment - but I/we can always port those. Think it's worth merging those in before doing this?

**Comment by matteofigus** [comment]
I guess another way to solve the problem of scripts minification is not to use javascript and have a completely old school server-side rendered set of pages, with no JS at all? 

This would quite be also consistent with the idea of switching away from etcd: while now we speak directly to the db, without it we would need to build an api layer to serve angular. So, building in html would just simplify things.

Just my 2 cents.

**Comment by stevejhiggs** [comment]
also sounds good. Right now the ui layer feels overcomplex for what it is.

**Comment by stevejhiggs** [comment]
merging in the ui tests would be good though as it gives me a loose spec

**Comment by tombuildsstuff** [comment]
@stevejhiggs I'll see what I can do :)

**Comment by ryantomlinson** [comment]
@chriscartlidge has also mentioned re-writing the UI in React @stevejhiggs . Might be worth having a chat before either of you waste time going in the wrong direction.

**Comment by chriscartlidge** [comment]
@stevejhiggs The plan was to hopefully spend sometime on this in Q1 to rewrite the front-end in React for pretty much the same reasons that you have listed.

I do like the simplistic approach that @matteofigus has suggested as for what the interface is hoping to achieve it really would work as well.

I'm happy if you want to take this up @stevejhiggs and we can focus on something else in Q1, if not no worries and I'd be keen to help you out, maybe create some cards in projects?
